services:
  dashy:
      build:  # Specify that the image will be built using the Dockerfile
        context: .
        dockerfile: Dockerfile
      env_file:
        - ./.env
      ports:
        - "8050:8050"
      networks:
        - containernetwork
  mysql:
    image: mysql:latest
    env_file:
      - ./.env
    ports:
      - "3306:3306"  # MySQL default port
    volumes:
      - mysqldata:/var/lib/mysql
      - ./project/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - containernetwork

volumes:
  mysqldata:  # MySQL data directory volume
networks:
  containernetwork:
